### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by miriamschroers** [ycba-cia/blacklight-collections2#104]

**Comment by yulgit1** [comment]
https://yale.app.box.com/s/l6pgsff9giglfusm3b0g3ej6g7olm0ae

Reviewed the checklist above, and made changes to comply in the custom code, adding semantic tags and alts for all images and svg. Commit here:
https://github.com/ycba-cia/blacklight-collections2/commit/6090a330513d97b6a2d092b778d5f62a3b1188b6

It's already being done to a limited extent, but it seems more could be done in blacklight core code as far as:
Use semantic markup to designate headings, lists, figures, emphasized text, etc.
Use ARIA landmarks and labels to identify regions of a page.
Define texts and text containers in relative units (percents, ems, rems) rather than in pixels.

But looking at other examples of blacklight, we are complying at the same level, so tending to say this is acceptable, especially as changing core code should be avoided for reasons of maintainability:
https://library.princeton.edu
http://findit.library.yale.edu/

**Comment by edgartdata** [comment]
@yulgit1 to set up meeting with Yale accessibility office.

**Comment by yulgit1** [comment]
relevant commits:
https://github.com/ycba-cia/blacklight-collections2/commit/db3e1c83b26697d6be08a51f8f0d8fd2c0e682db
https://github.com/ycba-cia/blacklight-collections2/commit/d2922441e113bf464ee7fe83fceeb3fadbe88015
https://github.com/ycba-cia/blacklight-collections2/commit/03e2985781ba196e342ca4583c194e0330a0a5aa
https://github.com/ycba-cia/blacklight-collections2/commit/68d2452d4a47c85fbfdc571b0457b0e0a2216c50
https://github.com/ycba-cia/blacklight-collections2/commit/5e8d3c37c656d35e3eebace4f6805cf35e75ccaa
https://github.com/ycba-cia/blacklight-collections2/commit/f4d677e11cd9bf3713bf433e294ea79ceb2eb769
https://github.com/ycba-cia/blacklight-collections2/commit/cd4397f1f88ad15f9dac7b526e1f0fe2f0cb37ae
https://github.com/ycba-cia/blacklight-collections2/commit/25e2aad69d4b4748332c6dc9d978e7b4f0d83953
https://github.com/ycba-cia/blacklight-collections2/commit/9bb4d0206f96844bec5f3b94dc229f927aa6f132
https://github.com/ycba-cia/blacklight-collections2/commit/4a4b423128bfcead755f398163d8a1ce7f4c4946
https://github.com/ycba-cia/blacklight-collections2/commit/aabf0b14692e13710c749014b1372fe6874c072c
