### ISSUE TITLE
handling missing images in search results

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#116]
for RB and  REF, use empty icon rather than grey box

**Comment by yulgit1** [comment]
Improvement over grey box: 
resolved via https://github.com/ycba-cia/blacklight-collections2/commit/07f64d9dfd2e2c8d5a4dba3551496615b3ed1981

@flapka OK?

**Comment by edgartdata** [comment]
@EdwardTown1 What would be your preferred icon for missing images for works of art? 

Yesterday with Eric we discussed a lighter gray box instead of the current dark gray one? Here is similar example from the Rijksmuseum. This is the webpage: https://www.rijksmuseum.nl/en/search?q=gerrit&ii=0&p=2 

![Rijksmuseum missing image icons](https://user-images.githubusercontent.com/4093644/54282614-c11cf700-4572-11e9-9520-ec6f03524779.jpg)

I like the idea of the missing image box saying something to the user as to why the image is missing, and I wonder if it might be possible to hard code such an image?

**Comment by flapka** [comment]
This may be another question for Matthew and Elisabeth and April. 

@yulgit1 I think I misspoke yesterday with my suggestion for book-y icons for RB items without images. Sorry. My hunch now is that it'd be better to follow suit with whatever we display for art objects that don't have images. The Rijksmuseum example is intriguing. 

Leaving it to @KraigBinkowski to chime in on what he thinks is best for Ref, when cover images aren't automatically retrieved (based on ISBN).

**Comment by KraigBinkowski** [comment]
I like the Rijksmuseum's grey boxes with a simple statement about Image not available. With Ref, and often with Rare, its not a question of copyright, but just that there is not an image available. I do think for consistency it might be best to have the same solution for books / art objects without images.

**Comment by EdwardTown1** [comment]
Agreed - good to have the information as to why the image is not or will
not be available. Light gray would be my preference

**Comment by edgartdata** [comment]
From @flapka : implement the same light gray icon in list view.

**Comment by yulgit1** [comment]
resolved https://github.com/ycba-cia/blacklight-collections2/commit/e12532ae41b794226092a1a457ceb3fef4dd044c

ok to close?
