### ISSUE TITLE
Arrangement of bib entries in collection record

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#149]
A determination must be made about the most useful arrangement for Publications (ie. citations, bibliography).

There is some contention, at this point @KraigBinkowski supports chronology, @EdwardTown1 support author alphabetically.

To support chronology we would need a lido field within relatedWork or relatedWorkSet for the Publication Year.  To support alpha sort, the sort could be done on the current citation itself, or the Author field must be passed (within relatedWork of relatedWorkset as a new lido field)

**Comment by robl** [comment]
As transition from this issue's precursor discussion in an email thread where I shared informal thoughts based on past work in a different type of role, this is just to note that I'm "officially" agnostic on this matter, which is outside the scope of my role here. Either approach can work.

**Comment by edgartdata** [comment]
@edgartdata to provide a separate LIDO element for authors of citations to allow for alphabetical ordering.

Authors and editors to be subjected to the same  alphabetical ordering.

Publications by unknown authors will go to the end of the list of bib citations. 

How many bib citations do not have authors or editors? @edgartdata

**Comment by edgartdata** [comment]
An update from me on this work: I have been working with David to add a full fledged Publication Event Set to LIDO DEV so that we can sort the authors and editors by their last names. We are almost ready to have this data ready in LIDO DEV and almost ready to pass it on to @yulgit1 to index.

**Comment by edgartdata** [comment]
@robl @edgartdata  need to work with David to make sure that authors, but also editors and contributors's names are included in the concatenation that we give Eric.

**Comment by edgartdata** [comment]
To check on after the data is refreshed this weekend.

**Comment by edgartdata** [comment]
@yulgit1 @EdwardTown1 @KraigBinkowski @flapka Would it be helpful to make each citation actionable, like the exhibitions, so that clicking on one bib citation would bring together all the objects discussed and/or illustrated in the bib item?

**Comment by edgartdata** [comment]
@yulgit1 Ed is in favor :)

**Comment by flapka** [comment]
I think I am in favor as well.

If we make the citations actionable, there may be a smidge of ambiguity about what will happen by clicking on the link. Some researchers may think that the link will take them to a description (record) of the publication.

**Comment by edgartdata** [comment]
@flapka suggests that we look into using some type of identifiers for publications so that we can bring RBM and art collections objects together through publications. It would motivate RBM to use a different MARC field that would need to be added to SOLR.
- post release.

**Comment by edgartdata** [comment]
Update: in order to ensure that the proper information is published in BlackLight bib citations, here are the rules by which COBOAT harvests data for BlackLight.

- Author (An author will be displayed at the beginning of the citation. If there are several authors, BlackLight will pick the #1 listed in TMS).
- Editor (An editor will be displayed at the beginning of the citation when there are no authors. If there are several editors, then BlackLight will pick the #1 listed in TMS)
- Contributor (A contributor will be displayed at the beginning of the citation when there are no authors and editors. If there are several contributors, then BlackLight will pick the #1 listed in TMS)
- Publisher (A publisher will be displayed  at the beginning of the citation when there are no authors, editors and contributors. If there are several publishers, then BlackLight will pick the one that has the term 'Yale' in it. If none have 'Yale' then BlackLight will pick one)

@KraigBinkowski While these rules are a little more strict than what we have been working with, they have the advantage of giving you full control of what constituents show up in the BlackLight citations. Let me know if you have any questions or if we should review this together.

**Comment by KraigBinkowski** [comment]
These seem fine to me as long as only one author/editor or contributor is published in the citations -- currently we are not adding multiple authors/editors to the bib module of TMS.  When no Author or editor or contributor is listed - does COBOAT simply omit?

**Comment by edgartdata** [comment]
Yes, when there are no author or editor or contributor, then COBOAT will look for a publisher instead.
