### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#153]
@yulgit1 Could we please have the current text that is right above the large image on the landing page moved to above the search box?

This is the text:
Welcome to Yale Center for British Art Collections Search
Enter an item to search, and/or use the facets on the left.

Also, could the text in the search box that currently reads as "Search..." be changed to "Search the collections"?
![Search box](https://user-images.githubusercontent.com/4093644/67507609-3dc19900-f65d-11e9-9b50-4a98af39d846.png)

This is to ensure that users understand more readily that this search box is to search the collections, not the website.

Thanks.

**Comment by yulgit1** [comment]
resolved:
https://github.com/ycba-cia/blacklight-collections2/commit/620c404a8e77819d3e20f9964bf6ce3866485800
to discuss: header move

**Comment by edgartdata** [comment]
@yulgit1 Just to reiterate what we discussed today, the text to move above the Search box is: Welcome to "Yale Center for British Art Collections Search", not the line that reads 'Enter an item to search, and/or use the facets on the left'

Although we did discuss changing 'Enter an item to search, and/or use the facets on the left' to 'Enter an item to search, and/or use the facets' since on mobile devices the facets might not always be on the left.

Also we talked about changing the word 'facets' for something else but I am not sure we came up with something we liked. @EdwardTown1  Any suggestions?

**Comment by yulgit1** [comment]
Implementation  of above moving the header from the splash section to above the search box with 1) desktop, 2) mobile aspect (will fix splash section if this change is desired)
@edgartdata @EdwardTown1 @robl
<img width="1430" alt="Screen Shot 2019-11-18 at 4 56 13 PM" src="https://user-images.githubusercontent.com/2125400/69097844-6c951a00-0a25-11ea-8512-b127793e87e5.png">
<img width="487" alt="Screen Shot 2019-11-18 at 5 01 30 PM" src="https://user-images.githubusercontent.com/2125400/69097870-774faf00-0a25-11ea-8c0e-af6f533e1346.png">

**Comment by edgartdata** [comment]
@yulgit1 That looks better to me. Could you delete the old 'Welcome...' that is just above the image?

**Comment by yulgit1** [comment]
@edgartdata  - Sure, that's what I meant by "fixing the splash section".  Should I go ahead and change the language to "'Enter an item to search, and/or use the facets'" as well while at it?

**Comment by edgartdata** [comment]
@yulgit1 It looks much better like this. It is clearer sign-posting for the users.

**Comment by yulgit1** [comment]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/2ed40fc7b5f5bd90e87ecfa5511a35272eb53301

**Comment by flapka** [comment]
I'm no designer, but my instinct -- supported a bit by example interfaces of other museum catalogs -- is that "Welcome to Yale Center for British Art Collections Search" is unnecessarily verbose. I wonder if the user needs a "Welcome" at all, especially when the header already provides the YCBA context. If we need one, I think shorter would be better, along the lines of "YCBA Collections Search."

**Comment by robl** [comment]
"YCBA Collections Search" could work for me, and would feel less redundant with the "Yale Center for British Art" header. As another variant, it could be made less of a title and more of a call to action as "Search the YCBA Collections" (and if so, with the prompt text within the search field then changed from "Search the collections..." to "Enter search term(s)...." Over to the collective wisdom re: whether that would make sense or not.

**Comment by edgartdata** [comment]
Extend the search bar all the way across the page
Welcome to the Collections Search
'Enter an item to search, and/or use the facets.' goes into the search bar
Keep 'Limit your search' above the facets.

**Comment by yulgit1** [comment]
2 issues with above suggestions (see screenshots):
1) The now longer string in the search box gets cut off within mobile view.
2) Due to limitation of the flex-grow boostrap parameter, the size of the input box can only grow a limited amount (see comparison below).  To do this also requires a monkey patch of a core blacklight library which should be avoided for long term maintainability.  Not sure it's worth it.

My suggestion:
1) In the search box use the shorter 'Enter terms to search'
2) Remove the 'Enter an item to search, and/or use the facets.' from the splash section. (Just keep the image)
3) Leave the search bar size the same
4) Make the 'Refine' change and make the 'Welcome to the Collections Search' change 

Thoughts?

<img width="1155" alt="Screen Shot 2019-11-22 at 5 01 34 PM" src="https://user-images.githubusercontent.com/2125400/69463933-02dd7e80-0d4b-11ea-9436-3d51a1818f85.png">
<img width="1151" alt="Screen Shot 2019-11-22 at 5 00 16 PM" src="https://user-images.githubusercontent.com/2125400/69463950-07a23280-0d4b-11ea-8917-376aa3d6b886.png">
<img width="480" alt="Screen Shot 2019-11-22 at 5 00 37 PM" src="https://user-images.githubusercontent.com/2125400/69463960-0bce5000-0d4b-11ea-9ae7-32d529c584ac.png">

**Comment by robl** [comment]
I like Eric's four-part suggestion above, with one small proposed copy-edit tweak. The "the" in "Welcome to the Collections Search" feels awkward to me, and I'd suggest that either "Welcome to YCBA Collections Search" or "Welcome to Collections Search" would be an improvement.

**Comment by edgartdata** [comment]
Welcome to Collections Search

**Comment by edgartdata** [comment]
Welcome to YBCA Collections Online

**Comment by yulgit1** [comment]
Above resolved including removal of image per Ed:

https://github.com/ycba-cia/blacklight-collections2/commit/3663cbc0a9f6b1b908efe70d3e9d3af76db4ab27
