### ISSUE TITLE
marc credit line

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#189]
"the credit line should go in the Holdings record (MFHD) – the same area as the item call number. (This would be a modification of the current credit line mapping for RB). Mapping the credit line would apply a similar technique to mapping a call number: we’d have to query the related Holdings record in the Voyager API, and retrieve data from the 583 field, as in this example."

**Comment by yulgit1** [comment]
@flapka 
Implemented:
https://git.yale.edu/ermadmix/camel_collections2/commit/77bd5f79aac00f1744c5d38894b1388cc9342512

Example:
http://ycba-collections-dev.herokuapp.com/catalog/orbis:583940

Full reindexing over the weekend

**Comment by flapka** [comment]
Thanks @yulgit1. Mostly looks good, but I notice now an unanticipated issue illustrated in this example: http://ycba-collections-dev.herokuapp.com/catalog/orbis:5428423 (and https://libapp.library.yale.edu/VoySearch/GetAllMfhdItem?bibid=5428423). Notice the two references to HathiTrust -- which apply to the LSF copy of the book, not the YCBA copy.

I see the need for two simple(-ish) fixes and one more complicated issue that goes beyond the 583 field (I'll put this in a separate message).

The two fixes:
1. When grabbing credit lines from the Holdings 583 field, the XSLT should ignore all <holding>s when the <mfhd_loc_code> is not from one of the bac sets (e.g. bacrb).
2. The 583 from the Bib record should always be ignored. We can add it to the exceptions for the "description" template in our XSLT.

**Comment by flapka** [comment]
@yulgit1 I notice one (new?) glitch this morning. For some records -- perhaps those recently indexed -- the credit line repeats, as in this example:

http://ycba-collections-dev.herokuapp.com/catalog/orbis:3283569 
"Yale Center for British Art, Gift of Joseph Reed, Yale BA 1954, and Kit Reed and Yale Center for British Art, Gift of Joseph Reed, Yale BA 1954, and Kit Reed" (I can confirm that this 583 appears only once)

Perhaps it shows up twice because it maps once from the bib record (541) and once from the MFHD (583)? For Blacklight, we can change the XSLT to ignore the 541 in the bib record, now that we're getting the credit line from the MFHD.

**Comment by flapka** [comment]
@yulgit1 @KraigBinkowski 

There's some crossover between this issue and https://github.com/ycba-cia/blacklight-collections2/issues/190, consolidated here.

Further points for attention, recapping our discussion on Friday:

1. To exhaustively retrieve all bac holdings, can we use bac* (instead of just bacrb, bacref, and bacia)? bacref has a number of subcodes, e.g. bacrefv

2. The mocked-up Holdings subsection generally looks good and can replace the separately listed fields for Collection, Credit Line, Call Number, and Access (i.e. the latter can be removed)

3. Ideally, this Holdings cluster of information would be placed between the fields for Physical Description and Copyright Status. If this proves challenging, we could certainly defer it for now but perhaps revisit in phase 5?

4. There was agreement in our meeting that it'd be better to omit the Holdings cluster labels for "Collection" "Callnumber" "Credit Line" and "Access", i.e. the data should stand well enough on its own, without label prefix.

5. If the Credit Line data is null, we'd like to omit the line altogether (rather than have "Credit Line: NA").

**Comment by yulgit1** [comment]
@flapka @KraigBinkowski 
above addressed: https://github.com/ycba-cia/blacklight-collections2/commit/a14fee6c1fa18034df146a9333b5a0eddd29ab79
