### ISSUE TITLE
Actionable links for external online resources

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#221]
@yulgit1 http://interactive.britishart.yale.edu/slavery-and-portraiture/330/commentary-by-daniel-roza is one of several links embedded in the publications for https://ycba-collections-prod.herokuapp.com/catalog/tms:107

Would it be possible to have these links resolve to their webpages? @KraigBinkowski's staff inputs them in a TMS field that unfortunately does not keep the link and I don't think it is possible in TMS. I might have to check with David on this if you think nothing can be done on your side.

**Comment by KraigBinkowski** [comment]
This information is recorded in the "Remarks" field in the Alternative Numbers section in the TMS Bib module. This request seems to go hand in hand with my request of #211 to link the bib entries to the full bibliographic record -- both add useful functionality to the bibs and increase ease of patron use.

**Comment by yulgit1** [comment]
I can't think of how this would be possible.  I don't think string manipulation of the citation would work as while you could get the substring starting with "http", there is no delimiter to indicate when the URL ends in the citation.

Otherwise it's the same challenge as #211, how to associate a bibid (or a URL in the cases with the linkable references) with the citation in indexable LIDO or through some not yet existing service? 

I am open to ideas.

**Comment by KraigBinkowski** [comment]
Is it possible for us to add some unique identifier (delimiter) at the end of each url - say a"|" so that we begin the citation as http and end it with | to enable string manipulation? If no, is there another field into which we can enter this info so that it can both be placed in the citation and also linked out to the url?

**Comment by flapka** [comment]
(With the danger of inserting comments in an issue for which my understanding is partial at best:)

For online resources in the TMS Bib module, what if we changed procedures (and remediated existing data) so that the URL is entered as the Alternate Number and the type value (Available Online) as the Description? Would that give us actionable data?

**Comment by edgartdata** [comment]
@edgartdata to test Alternate Numbers and Description (for URL) with David Parsell.

**Comment by yulgit1** [comment]
In addition to actionable links, we need a new delimiter (not forward slash) for italics. In the Roza LIDO apellationValue element:

Daniel Roza, /Commentary on a Group Portrait featuring Elihu Yale by an unknown artist, [ Website ], /Yale Center for British Art, Accessed 11/30/2015, 4:26 minutes, Available Online , http://interactive.britishart.yale.edu/slavery-and-portraiture/330/commentary-by-daniel-roza

becomes (stripping the forward slashes in the url to italics tags, which isn't visible here due to GitHub formatting cut and pasting into this issue):

Daniel Roza, Commentary on a Group Portrait featuring Elihu Yale by an unknown artist, [ Website ], Yale Center for British Art, Accessed 11302015, 4:26 minutes, Available Online , http:interactive.britishart.yale.eduslavery-and-portraiture330commentary-by-daniel-roza

To fix this, any delimiter not found in the text would work say ^ surrounding italics and * surrounding links.  @edgartdata Is this even doable within TMS or coboat?  Seems like a lot of manual intervention.

**Comment by edgartdata** [comment]
@yulgit1 I will check with David. To recap this issue (let me know if I misinterpreted it in any way please): we need a new delimiter (not forward slash) for italics (in titles but also in citations) because we want to use forward slashes only as part of URLs to web resources. On your side @yulgit1 you will have some logic in BlackLight to dereference these http://... strings to be actionable links. Do I have it right?

**Comment by yulgit1** [comment]
Yes, a delimiter for italics and a delimiter from the URL string. Any character will work this is not found natively in the apellationValue field.  Indexing logic will dereference these.

**Comment by edgartdata** [comment]
@KraigBinkowski http resources that get used in bib citations/publications are currently coming from multiple fields in TMS. For example, the _Figures of Empire_ website links are captured in the _Alternate Number Remarks_ field, and the YouTube links are captured in the _sub-title_ field. It would make the process to make these links actionable online easier if all http links were captured in TMS in the same field. Is it appropriate? Are there other TMS fields other than these 2 used for this type of data?

Also, now that we are so close to having the http links in the TMS Alternate Number Remarks field actionable in BlackLight, these links will need to be verified as some of them may have become broken (welcome to the instability of the web!), and others are not to specific enough to bring users to the exact webpages described in the citation. I have included a short list of 52 bib records that have http links in the TMS Alternate Number Remarks field.
[bib citations with http.xlsx](https://github.com/ycba-cia/blacklight-collections2/files/4955591/bib.citations.with.http.xlsx)

**Comment by KraigBinkowski** [comment]
OK - if the TMS alternative number field will show on the bib and be actionable - lets put all urls there.  Is it possible to have a report of the citations that include the url in the subtitle? then we can transfer those to alt fields and check all the links. I can have staff work on this right away.

**Comment by edgartdata** [comment]
@KraigBinkowski here are 48 TMS Bibliography Module records that have http resources in the subtitle field. As noted above, let us know when these URLs are moved to the Remarks field, as attached.

![http links in tms for bib resources](https://user-images.githubusercontent.com/4093644/88328151-053b1280-ccf6-11ea-874e-a76f76e9d7b0.png)

**Comment by edgartdata** [comment]
@KraigBinkowski I am linking here the spreadsheet prepared by David Parsell with:
- Remarks              URLs and other non-url data. There are about 50 URLs located about 3/4s of way through the file. This data is not included in the citation at this point.
- Citation                 Rest of the fields except remarks that comprise the citation.
- Title                       Title and sub-title fields are included so you can check citation formatting with and without both title fields. I think double comma problem is fixed.
- Sub-title

I hope it is helpful to spot which subtitles need tidying up in TMS.
[TMS Bib Module title subtitle.xlsx](https://github.com/ycba-cia/blacklight-collections2/files/4973060/TMS.Bib.Module.title.subtitle.xlsx)

**Comment by yulgit1** [comment]
actionable links enabled: https://github.com/ycba-cia/blacklight-collections2/commit/41e3a3271249164477bfd5c4d5389008574fd609

full indexing tomorrow

**Comment by edgartdata** [comment]
The links are not in production and actionable in BL. 
More links will be added to citations as we clean up TMS BIB Module.
