### ISSUE TITLE
Request Photography rare books form

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#227]
From email thread: Re: Rare Books and Manuscripts image request webform

Suppress for REF, IA
Implement RB:
     https://britishart.yale.edu/request-images-rare-books-and-manuscripts
Implement keep for PD,PS,FR:
     https://britishart.yale.edu/request-images

**Comment by yulgit1** [comment]
implemented: https://github.com/ycba-cia/blacklight-collections2/commit/f42b9526f48e68836a9fdb7cba785b7e6f75f269

**Comment by flapka** [comment]
@yulgit1 The RB form is implemented, but there are two fields that need tweaking to fully auto-populate the request form. 

[Here's](https://britishart.yale.edu/request-images-rare-books-and-manuscripts?id=&num=&collection=Rare%20Books%20and%20Manuscripts&creator=Somerville,%20William,%201675-1742&title=The%20chase.%20A%20poem.%20By%20Wiiliam%20Somervile,%20esq.&url=http://hdl.handle.net/10079/bibid/3379107) an example request.

You'll see that the Identifier and Call number fields are blank. Can we pass those parameters too? I acknowledge that Call number is tricky -- since a record may have more than one, and the request link can't specify which is of interest. Is it possible to make a rule by which the call number is passed if there is only one?

Thanks!

**Comment by yulgit1** [comment]
@flapka 
addressed: https://github.com/ycba-cia/blacklight-collections2/commit/5b548fa622f3f1a5f9fbcf2729f429d7aa6a8831
