### ISSUE TITLE
Text Categories (curatorial, labels, catalog entries)

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#275]
In an email exchange, @edgartdata and I identified the following as a topic for discussion in CIA & Friends.

In TMS, the plan is to commit to the following categories for now, and possibly create more in the future:
* Curatorial comments: with author's names
* Gallery wall label, including temporary “pop up” exhibits: do not include authors’ names except when the labels are written by non-curatorial YCBA staff members
* Text written for entry in a publication/exhibition catalog or brochure to describe an object: with authors’ names and titles of exhibitions when applicable

I'd like to rationalize practice in RB, and make it consistent with art collections cataloging. Several questions:
1. What’s the rationale for omitting the authors’ name if written by non-curatorial YCBA staff members? 
2. Would it be useful to append a date for each category of text? 
3. How do we envision that the text categories will display in Blacklight?

**Comment by KraigBinkowski** [comment]
Any way to link the "text written for entry in a publication..." to the record for the publication in BL?

**Comment by flapka** [comment]
I like @KraigBinkowski 's suggestion. Where such texts exist in description of an RB item (in MARC), I think the pertinent field would provide a mechanism for making that sort of link.

**Comment by yulgit1** [comment]
(1)
I don't know the actual rationale, but it would make sense to me that an in house wall label is understood implicitly as a work of the museum.
(2)
We are vending author/date already with CC, Prue for ex:
https://collections.britishart.yale.edu/catalog/tms:5005
(3)
I like Kraig's suggestion, if that info can be stored and exposed in TMS, and it could possibly use the [[]] strategy for the links.

**Comment by EdwardTown1** [comment]
Hi all: Emmanuelle and I have worked up this list of cataloguing guidelines for the mixed bag of prose text that has hitherto been described as Curatorial Comments. Ahead of putting this in front of Martina and the Curatorial group we wanted to ask for your feedback on the attached document:

Look forward to hearing your thoughts! 
 
[YCBA object descriptive texts_EDG_ET_12.17.2020.docx](https://github.com/ycba-cia/blacklight-collections2/files/5711768/YCBA.object.descriptive.texts_EDG_ET_12.17.2020.docx)

**Comment by KraigBinkowski** [comment]
Dear Ed and Emmanuelle,

Thanks for sending this - are the entries in the "Published Catalog" the actual full text from the catalog?  If so, this placement seems appropriate though it would be good to be able to make certain in some way that this information is conveyed to us in the library (or to someone) so that we can indeed add the citation to the full bibliography if it isn't already there. Finally, the link to the full Library BL record from the citation is the same functionality that I requested for the bibliographies and is open issue #211. Both should be doable.


     *   Published Catalog Entry: YCBA exhibition catalog entries, YCBA scholarly publications, and brochures be they printed, online or both.
        *   Authors are credited. First name, Last name.
        *   Date of publication. Month, Year.
        *   At the end of the prose block provide context/citation and link to the YCBA Ref Lib BL resource record from the BlackLight citation, such as: Ellen D'Oench, The conversation piece: Arthur Devis & his contemporaries, New Haven: Yale Center for British Art, 1980.
My best,

Kraig

Kraig Binkowski
Chief Librarian
Reference Library and Archives

Yale Center for British Art

1080 Chapel Street

P.O. Box 208280

New Haven, CT 06520-8280

+1 203 432 2846 | +1 203 415 1192 mobile


britishart.yale.edu<http://britishart.yale.edu/>

Explore the Center's exhibitions<https://britishart.yale.edu/exhibitions> online.
Connect on Facebook<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FYaleBritishArt%2F&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312502268&sdata=cWFWX9dZKjaC9SiTfDHkWQmsW0fv5Y%2B9aaSfG%2FWSo%2BA%3D&reserved=0>, Twitter<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FYaleBritishArt&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312512260&sdata=IFyktJi9i3QXR94LWitH5svX0D%2F9pQ8Bb4Vjjm8BWGI%3D&reserved=0>, Instagram<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fyalebritishart%2F&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312512260&sdata=7hZ4%2BD6l1XUl13qTvjpB56lQ8hVH4VvnrhhR3lnKG4w%3D&reserved=0>, and YouTube<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fyalebritishart&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312522255&sdata=RQmjS7zAcuAEdlGLt55LVMHp7gds5pqmys3g2PPxlWk%3D&reserved=0> @yalebritishart #YCBA

**Comment by yulgit1** [comment]
So there could be all 3 (Published Catalog Entry, Gallery Label, and Online curatorial comment), and multiple of each?  To be entered into TMS, exposed in LIDO as an event set? If so would that preclude any ordering other than that which can be inferred by a date or name?  Also how exactly to format the prose block+citation for each on the blacklight page (indentation, bold,italic, size etc).

**Comment by edgartdata** [comment]
@KraigBinkowski I agree: a process needs to be put in place with you/your team for synchronization of the Published Catalog Entry and the bibliographic citations further down in the detailed object/item record.
Looking for @yulgit1's guidance on how to make actionable the bib citations that are in detailed object records so that they link to BL Reference Library item records.

**Comment by edgartdata** [comment]
@yulgit1 Why don't we draft our ordering recommendations for these scenarios together in CIA & Friends and then Ed and I are happy to submit them to Martina?

For your second question, right now with the way we are recording the data in TMS (prose block+citation in one text entries field, with date and name of one author in 2 additional separate fields) and the way we are transforming it through COBOAT, it is not possible to vend text formatting. We "might" not need italics if we can at least preserve the line jumps/carriage returns of the prose block+citation in the TMS text entry. We might need to put that question to Gallery Systems however as it has been a stumbling block for some time now.

**Comment by yulgit1** [comment]
Actionable bib citations would depend on vending along with the citation the bibID.  For example 579300 with the D'Oench 1980.

**Comment by edgartdata** [comment]
Let's put aside for a moment the issue of linking BL Reference Library citations that are in the detailed BL object records to BL Reference Library detailed records for these publications to focus on the format and business rules for the 3 categories of descriptive texts proposed above.
For convenience, here is the proposal:

**Published Catalog Entry**: YCBA exhibition catalog entries, YCBA scholarly publications, and brochures be they printed, online or both.
- Authors are credited. First name, Last name.
- Date of publication. Month, Year. 
- At the end of the prose block provide context aka the citation to the YCBA Reference Library BL resource record as it is (ideally) already noted in the BL Publications section of the detailed painting/item record, such as: Ellen D’Oench, The conversation piece: Arthur Devis & his contemporaries, New Haven: Yale Center for British Art, 1980. 
- @KraigBinkowski @flapka Please note this change from an earlier version of this proposal: on 12/18 we agreed that this context/citation would not be a hyperlink pointing to the YCBA Reference Library BL resource record and this for 2 reasons. The first reason is that would not be easy to add the Orbis bibID to the TMS Text Entry where the Published Catalog Entry is entered. The second reason is that ideally the publication citation providing the context for the Published Catalog Entry has already been entered in the Publication section of the item/painting and is hyperlinked to the YCBA Reference Library BL resource record. In other words, we probably don't want to have the same resource linked twice in 2 different places in the same detailed item/object record.


**Gallery Label**: Permanent collection wall labels, YCBA exhibition wall labels, and YCBA digital born exhibition wall labels.
- Author not credited, unless they are a YCBA non-curatorial staff member (this might/can be decided and implemented in TMS on a case by case basis), in which case the format First name, Last name will be adopted
- Date of writing. Month, Year.
- Context provided (but, for the same reasons as above, not as a hyperlink): exhibition citation on the model of what we are doing now/is ideally already noted in the Exhibition History section of the detailed item/object record: ex.: Sir Joshua Reynolds (RA) Réunion des Musées Nationaux, 1985-19-07 – 1985-12-16
- Or ‘Gallery Label for installation of permanent YCBA collection, Month, Year’. 

**Online Curatorial Comment**: YCBA digital born curatorial comments, with no immediate context of a publication (printed or online), exhibition or installation of the permanent collection. 
- Author credited. First name, Last name.
- Date of writing. Month, Year. 

Business rules:
- @EdwardTown1 @flapka When an object has texts in all 3 categories, what is the order of the categories? (@edgartdata will need to work with David to change the COBOAT script to accommodate for this scenario of multiple texts in one category for one object, as currently COBOAT only publishes one curatorial comment per object)
- One object/item can have multiple descriptive texts of each categories. When it happens, @EdwardTown1, should they be ordered chronologically? Descending or ascending order? @yulgit1 can you publish them to BL by sorted by their dates? 
- What to do when the Published Catalog Entry and the Gallery Label are almost the same for one object? (In TMS it is possible to turn on or off any of these three categories of text easily).

Workflow questions:
- What is the editorial process? For example, who edits the Online Curatorial Comment? 
- What is the workflow for data entry of these texts into TMS?
- How to make sure that publications noted as context for the Published Catalog Entry and the Gallery Labels are also recorded as TMS bibliographic citations in the BL Publications section? Should the person/departments who enter the descriptive texts into TMS also coordinate with the Reference Library?

**Comment by KraigBinkowski** [comment]
Workflow Questions: 
  How to make sure that publications noted as context for the Published Catalog Entry and the Gallery Labels are also recorded as
  TMS bibliographic citations in the BL Publications section? Should the person/departments who enter the descriptive texts into 
  TMS also coordinate with the Reference Library?

It would be helpful if the person who adds the published texts into TMS also checks the bibliography to make certain the text is represented there. If it is not, a message should be sent to the Ref Library to add it.

**Comment by flapka** [comment]
At the end of our last meeting, I alluded to the fact that there are examples of descriptive text in library/archive descriptions that may imperfectly fit with the three established categories. In Blacklight, these examples appear under the heading of "Notes."

Here are some of the most prevalent types of variant library/archive descriptive texts:

1. Descriptions provided by the artist (exclusively? in RB). Example: https://collections.britishart.yale.edu/catalog/orbis:15657871 

2. Descriptions, composed by cataloging staff, that provide a summary of the material and/or biographical historical context (mostly in RB and IA, some in Ref?). Example: https://collections.britishart.yale.edu/catalog/orbis:14447565

3. Quotations from a book (etc.) that provide a useful summary of the content (RB, Ref). Example: https://collections.britishart.yale.edu/catalog/orbis:12961206 

I offer these examples without assumption on whether we should alter their treatment. It may in fact be preferable to keep such text as "notes," especially if treatment in the three categories requires external copy editing.

**Comment by edgartdata** [comment]
@flapka thanks for providing these RBM examples. Here are my thoughts based on this limited set of examples:

1. Descriptions provided by the artist (exclusively? in RB). Example: https://collections.britishart.yale.edu/catalog/orbis:15657871 

Could potentially fit nicely in the **Online Curatorial Comment** category?
Note: I do not know of comparables in the art collection, @EdwardTown1 are there any? Would the art collection possibly engage with contemporary artists to provide such descriptions in the future?

2. Descriptions, composed by cataloging staff, that provide a summary of the material and/or biographical historical context (mostly in RB and IA, some in Ref?). Example: https://collections.britishart.yale.edu/catalog/orbis:14447565

Maps to **Online Curatorial Comment** category as well?

3. Quotations from a book (etc.) that provide a useful summary of the content (RB, Ref). Example: https://collections.britishart.yale.edu/catalog/orbis:12961206

Seems to map nicely to **Published Catalog Entry**

Question to @flapka Would RBM be interested/able to contribute exhibition labels?

My sense is also that we would probably (?) not want to edit text provided by artists, and that entries for the Published Catalog Entry category would already be going through their own editing process either for exhibition or publication. So that would only leave the descriptions written by staff and I understand that this clashes somewhat with long established library practices, which includes writing such paragraphs. 

Is think that it would be helpful to users to map as much of the RBM descriptive content to the 3 categories above but we also want to balance this effort with established practices.

**Comment by edgartdata** [comment]
Let's try finalize the proposal this friday so that we can put it in front of Martina soon.

**Comment by yulgit1** [comment]
Do these all have to fit to to those 3 labels? Meaning could the museum use:

Published Catalog Entry
Gallery Label
Online Curatorial Comment

While library uses:

Creator Description
Curatorial Comment
Excerpt From work

Or something to that effect?

**Comment by flapka** [comment]
I'd like to mull over (and hear the thoughts of others) on @yulgit1 's questions.

To @edgartdata 's thoughtful suggestions:

1. Descriptions provided by the artist: If we were to treat these as a type of Curatorial Comment, we'd have to alter the definition of that category, as it is currently scoped to YCBA authorship. And does it make sense to label it "curatorial" if the source is the artist?

2. Summaries / context devised by cataloging staff: I agree, such text is in the vicinity of Curatorial Comments. My hesitancy is rooted in the variation found in such summaries to date: some are short and hasty, others are longer or more refined. If we were to apply the curatorial comment label to this category, we might wish to do so selectively. The question of word count might be one factor in this consideration.

3. Quotations from a book (etc.): Here again I agree, this text is similar in character to "Published Catalog Entry," except that the category is currently scoped to YCBA authorship. 

I leave it to Kraig and Rachel/Cate to speak with the perspectives of Ref and IA.

**Comment by edgartdata** [comment]
@flapka @edgartdata all, here is my attempt at documenting our decisions today. Feel free to correct as necessary.

RBM descriptions provided by artists will go to a new category '**Artist's statement**' (@flapka to find a way to map these approx. 100 RBM entries to this category) - EDG: can we suggest a word count of approx. 150?

Summaries / context devised by RBM cataloging staff will go to **Online Curatorial Comments**. - might need to be edited as part of this new process. - Online Curatorial Comment renamed **Curatorial Description** for all YCBA departments. Text in this category can be slightly longer than text in the other categories, i.e. be around 200 words.

RBM quotations from a book (etc.) goes to a new category (only used by RBM): **Summary** - EDG: can we suggest a word count of approx. 150?

This is a data project that will require some time for RBM to implement as it requires much retrospective cataloguing. EDG: One way to prioritize the work might be to work first on text for the Curatorial Description category, as it seems that there are already drafts in P&D and RBM ready to be edited. @flapka @EdwardTown1 agree?

@rchatalbash @peeblesc Can you let us know how prose text from your collection might fit into any of these categories. If they don't work for you, can you suggest names for your categories, with a description of what they would be?

**Comment by peeblesc** [comment]
@edgartdata From an Archives perspective, we're on board with including our Scope and Content and Biographical/ Historical note description under the 'Curatorial Description' umbrella. However, if word length is important, we might like to discuss this further, as many, if not most, of our combined S&C/ BiogHist notes would end up being more than 200 words. @flapka says this is the case for RBM too.

**Comment by flapka** [comment]
> RBM descriptions provided by artists will go to a new category 'Artist's statement' (@flapka to find a way to map these approx. 100 RBM entries to this category) - EDG: can we suggest a word count of approx. 150?
FL: The [example named above](https://collections.britishart.yale.edu/catalog/orbis:15657871) is 168 words. Would 150 words be a loose target rather than a hard limit? That would seem reasonable to me.

> RBM quotations from a book (etc.) goes to a new category (only used by RBM): Summary - EDG: can we suggest a word count of approx. 150?
FL: As above, this sounds reasonable to me.

> This is a data project that will require some time for RBM to implement as it requires much retrospective cataloguing. EDG: One way to prioritize the work might be to work first on text for the Curatorial Description category, as it seems that there are already drafts in P&D and RBM ready to be edited. @flapka @EdwardTown1 agree?
Given current capacity, I think progress will have to be rather measured. It will require time-consuming review of records, one by one. Necessary steps include:
1. Determine a creative way to implement the text categories in MARC.
2. Determine copy-editing preferences / capacities.
3. Supply a steady stream of texts for review.

As @peeblesc notes, the 200-word cap on Curatorial Descriptions -- though perhaps a reasonable benchmark for future work -- may be problematic for existing text. Where the current descriptions already exceed 200 words, I suggest that it would be a better use of time to grandfather them in as is, rather than rewrite.

**Comment by edgartdata** [comment]
All, Please find below the guidelines we intend to submit to Martina for descriptive texts after our meeting tomorrow. Indicate in this thread if you have edits, suggestions or concerns. (thanks to @flapka and @peeblesc for their collaboration on this).

YCBA object descriptive texts-cataloguing guidelines

- **Curatorial Description** (formerly Online Curatorial Comment): TMS, RBM, IA born-digital curatorial comments, with no immediate context of a publication (printed or online), exhibition or installation of the permanent collection. 

    - Author credited. First name, Last name
    - Date of writing. Month, Year
    - Word count: TMS records will aim for about 200 words; IA and RBM might have longer texts
    - For finding aid descriptions of archival collections (IA and RBM), Scope and Content notes and Biographical/Historical notes will map to this category
    - RBM descriptions, composed by cataloging staff, that provide a summary of the material and/or biographical historical context will also map to this category

- **Published Catalog Entry**: YCBA exhibition catalog entries, YCBA scholarly publications, and brochures be they printed, online or both.

    - Authors are credited. First name, Last name
    - Date of publication. Month, Year
    - At the end of the prose block, add the BlackLight publication citation the published catalog entry refers to: Ellen D’Oench, The conversation piece: Arthur Devis & his contemporaries, New Haven: Yale Center for British Art, 1980. (see link below)


- **Gallery Label**: YCBA permanent collection wall labels, YCBA exhibition wall labels, and YCBA born-digital exhibition wall labels 

    - Author not credited, unless they are a YCBA non-curatorial staff member 
    - Date of writing. Month, Year
    - At the end of the prose block, add the exhibition citation as it is referenced in the Exhibition BL section: 
Sir Joshua Reynolds (RA) Réunion des Musées Nationaux, 1985-19-07 – 1985-12-16
or 
Gallery Label for installation of permanent YCBA collection, Month, Year


- **Artist's statement**: RBM item descriptions provided by artists

    - Author credited. First name, last name
    - Date of writing: Month, Year
    - Word count: about 150 words (not a hard limit)

    
- **Excerpt from Publication**: A portion of text quoted from a book, etc. (because it serves as an effective summary of the work) provided by RBM

    - Author credited. First name, Last name
    - Date of writing. Month, Year
    - Word count: about 150 words (not a hard limit)

**Comment by yulgit1** [comment]
Where will these go, above "Exhibition history"?

Would there be some redundancy in having "Published Catalog Entry" citations, and "Publications".

Would there be some redundancy in library "Notes" and" "artist statement" or "except from publication"?

**Comment by flapka** [comment]
> Would there be some redundancy in library "Notes" and" "artist statement" or "except from publication"?

Redundancy should be avoidable. Text that RBM treats as "artist's statement" or "excerpt from publication" will have encoding to differentiate from "notes" (and we can implement new mappings to capture the distinct encoding).

**Comment by KraigBinkowski** [comment]
"Would there be some redundancy in having "Published Catalog Entry" citations, and "Publications"."

I believe the "Published cat entry" will be the actual entry with a citation included. The "Publications" would have the same citation, yes, but will sit in the context of all the other bib citations which will eventually be linked to the full bib records.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Exploring anew how to implement this in MARC. Is there a functional requirement (or benefit) to have the author's name and date each in separate fields? It's okay to say 'yes', though it adds to the challenge.

**Comment by yulgit1** [comment]
@flapka yes for sorting functionality
