### ISSUE TITLE
Adding Orbis BibIDs to new TMS Bib module records

### ISSUE THREAD

**Issue by KraigBinkowski** [ycba-cia/blacklight-collections2#279]
Going forward, when new bib records are added to the TMS Bib module, we will include the Orbis BibID. 
“Orbis BibID” will be a drop down choice  in the **Description** field and the actual BibID will be entered in the **Alternate Number** field. 
@azaroth42 @flapka Any concerns or suggestions about this going forward?

**Comment by edgartdata** [comment]
@KraigBinkowski @flapka Today in the LUX PoC meeting, we talked about leveraging the OCLC, ISBN, and LCCN identifiers in our items descriptions. @kraig Could we please capture them in the TMS Bibliography Module going forward? Or is there a way to programmatically harvest them from Orbis, or WorldCat from our Orbis BibID to avoid manual labor and typos? @azaroth42 might have a suggestion for this?

**Comment by KraigBinkowski** [comment]
We do already record OCLC number -- though that just started about a year or so ago. As for the rest, it is certainly possible to record them as we work on the record, but I would prefer to harvest them periodically post-creation using the bibid to match. This takes the job out of the hands of our mistake-prone and slow-moving students. The whole process is quite labor intensive already and I would like to explore any way we can to make it less-so on our end.

**Comment by flapka** [comment]
Yes, adding the Orbis Bib ID would clearly be beneficial. 

Seems like we should be able to programmatically add most of the missing information. To start, it might be helpful if we could get an export of all records in the TMS module, each with *all* categories of alternate number already assigned. Have we made any progress on the difficulties documented in issue #211?

For the export above, I suppose the essential is just the alternative numbers table, joined one or two pieces of essential identifying information describing the bib (e.g. title, ReferenceID).

**Comment by edgartdata** [comment]
@flapka We have not made progress unfortunately and with the TMS/CS upgrade upon us next week, we are going to have to wait until the week of November 2.
In the meantime I will work out the LIDO XML structure necessary to receive additional identifiers such as OCLC and Orbis BibID for our TMS bib citations.

**Comment by KraigBinkowski** [comment]
Complicating this export of alternative numbers assigned is the fact that for a couple of years in the beginning of the project we imported bib records from Voyager to TMS via Z39.50 protocol. This proved too labor intensive but for all those records imported in that way, there are many Alternative numbers recorded that we did not record subsequent to Z39.50.

**Comment by edgartdata** [comment]
Goog news: actually we already vend several bib citation identifiers to LIDO, as shown below, so no need to expand our LIDO structure. I do need to still circle back to David Parsell because right now it looks like we are only vending YCBA (TMS Bib Module record ID), LC Call Number, and OCLC Number to LIDO. I will add ISBN to the list of identifiers to push to LIDO. 

<lido:relatedWorksWrap>
<lido:relatedWorkSet>
<lido:relatedWork>
<lido:displayObject>Julia Marciari-Alexander, This other Eden, paintings from the Yale Center for British Art, Yale Center for British Art, New Haven, CT, 1998, pp. 14-17, fig. 14, ND1314.3 Y36 1998 (YCBA) </lido:displayObject>
<lido:object>
<lido:objectWebResource/>
<lido:objectID lido:type="local" lido:source="**LC Call Number**">ND1314.3 Y36 1998 (YCBA)</lido:objectID>
<lido:objectID lido:type="local" lido:source="**OCLC Number**">38239347</lido:objectID>
<lido:objectID lido:type="local" lido:source="**YCBA**">45</lido:objectID>
<lido:objectNote/>
</lido:object>

**Comment by flapka** [comment]
Excellent. To be clear, are we asking to add ISBN *and* Orbis ID to the list of identifiers to push to LIDO? 

This is an example of a bib record that already has an Orbis ID in alternative numbers (as "control number") that's not vended to LIDO (so far as I can see):
`
<lido:relatedWorkSet>
<lido:relatedWork>
<lido:displayObject>On the trail of Turner in North and South Wales., Cadw, Cardiff [Wales], 1995, p. 32, NJ18 T85 O56 1995 (YCBA) </lido:displayObject>
<lido:object>
<lido:objectWebResource/>
<lido:objectID lido:type="local" lido:source="LC Call Number">NJ18 T85 O56 1995 (YCBA)</lido:objectID>
<lido:objectID lido:type="local" lido:source="YCBA">700</lido:objectID>
<lido:objectNote/>
</lido:object>
</lido:relatedWork>
<lido:relatedWorkRelType>
<lido:conceptID lido:type="local" lido:source="publication"/>
<lido:term>related to</lido:term>
</lido:relatedWorkRelType>
</lido:relatedWorkSet>
`

**Comment by edgartdata** [comment]
@flapka You are absolutely right: as shown below in the TMS screenshot, we already have these additional identifiers in TMS for this bibliographic resource and I will include both in my request to David P.
Today, we have 907 TMS Bibliography Module citation records (not links to works of art) with a Call Number. We also have 585 bib citation records with ISBN identifiers.
Question for @KraigBinkowski and you @flapka: In TMS do we want to rename the identifier currently called 'Control Number' as 'Orbis ID'? I realize that the appellation 'Control Number' is meaningful in libraries but I am wondering if it might become less so outside of that context? I will wait for your answers before putting the request out to David. Also are there other identifier types that we should include?
![TMS Bib Module multiple identifiers](https://user-images.githubusercontent.com/4093644/96889311-794f9880-1454-11eb-8765-4241f5761861.png)

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski To anticipate long-term changes, I'd suggest a label that's more neutral, omitting Orbis (which could be retired in the next 5 or 10 years). Perhaps Library ID, YUL ID, or Yale ID? What do you think Kraig?

**Comment by edgartdata** [comment]
@yulgit1 This planned expended use of LIDO impacts you as well because I think (please correct me if I am wrong) that you currently map our TMS bibliographic citations that are in eventType=publication event to for PoC schema Citation String Display. Unfortunately the eventType=publication event does not accommodate for identifiers of bib resources (it can only have identifiers for the event):

<lido:eventSet>
<lido:event>
<lido:eventID lido:type="TMS">1452</lido:eventID>
<lido:eventType>
<lido:conceptID lido:source="AAT" lido:type="local">300054686</lido:conceptID>
<lido:term>**publication event**</lido:term>
</lido:eventType>
<lido:eventName>
<lido:appellationValue>Ingrid Roscoe, ^A biographical dictionary of sculptors in Britain, 1660-1851^, Yale University Press, New Haven, CT, 2009, p. 268, no. 102, NB496 B56 2009 (YCBA) (Wall Shelf 3) Also available in online database (Herts [England] : The Henry Moore Foundation, 2010-) : see Orrbis record for link. to internet resource </lido:appellationValue>
<lido:sourceAppellation>Yale Center for British Art</lido:sourceAppellation>
</lido:eventName>

Instead, I suggest that you use the TMS bib citations that we push to lido:relatedWorkSet, which is a set that does allow for identifiers (and multiple identifiers) for bib resources, as you can see we are already vending to LIDO below:

<lido:relatedWorksWrap>
<lido:relatedWorkSet>
<lido:relatedWork>
<lido:displayObject>Ingrid Roscoe, A biographical dictionary of sculptors in Britain, 1660-1851, Yale University Press, New Haven, CT, 2009, p. 268, no. 102, NB496 B56 2009 (YCBA) (Wall Shelf 3) Also available in online database (Herts [England] : The Henry Moore Foundation, 2010-) : see Orrbis record for link. to internet resource</lido:displayObject>
<lido:object>
<lido:objectWebResource/>
<lido:objectID lido:type="local" lido:source="LC Call Number">NB496 B56 2009 (YCBA) (Wall Shelf 3)</lido:objectID>
<lido:objectID lido:type="local" lido:source="OCLC Number">317471782</lido:objectID>
<lido:objectID lido:type="local" lido:source="YCBA">1732</lido:objectID>
<lido:objectNote/>
</lido:object>
</lido:relatedWork>

Please let me know if you have questions or concerns about this.

**Comment by KraigBinkowski** [comment]
Yes, I think a more generic name would be sensible. I don't have a preference for Lib ID, or even Bib ID.
Emmanuelle, when you say "today, we have 907 TMS Bibliography Module citation records.. with LC Call Numbers" -- do you mean that is the count of all the bib records with LC call numbers in the TMS Bib module? if so, that number should be much higher -- every bib record that we add to TMS has an LC number and last year alone we added over 400 book/article titles (not citations) to the module. For the sake of this Issue, the exact numbers probably don't matter, but it is concerning to not be able to get an accurate count -- if I understand your statement.

**Comment by edgartdata** [comment]
LC Call Number
OCLC Number
ISBN
Orbis BibID/ILS#...name tbd (LUX question)

**Comment by edgartdata** [comment]
@KraigBinkowski @flapka Circling back to this issue (that is related to https://github.com/ycba-cia/blacklight-collections2/issues/275) I think the hold up here is an agreed name for Orbis BibID. What would make sense for us and in the LUX context?

**Comment by edgartdata** [comment]
@yulgit1 I just wanted to confirm with you that you are using the TMS bib citations that we push to lido:relatedWorkSet for the LUX publications? lido:relatedWorkSet is where we vend publications external indentifiers (LC Call Number, OCLC Number, ISBN, Orbis BibID/ILS#).

**Comment by yulgit1** [comment]
We are using the appellationValue for those that are "publication event", not the relatedWorkSet, as the former has the carets used for formatting italics.

But as long as the ordering is the same, which it is for B1977.14.77 checking the first few publications, we can pull the BibIDs that would be there.  But looking now there are no bibIDs yet (Only LC Call Number, OCLC Number, and YCBA local):

https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:34&metadataPrefix=lido

**Comment by edgartdata** [comment]
@yulgit1 the LIDO publication event element does not have the structure for bibIDs. Only the relatedWorkSet does so we would have to ask David to move his caret script to the relatedWorkSet.
And yes, the bibIDs are not in the relatedWorkSet yet because Kraig, Francis and I have to agree on a name for it first, which we will do at our first CIA & Friends meeting in January 2020 👍 
Happy holidays Eric!

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski @yulgit1 

On the question of a neutral label in place of "Orbis" it wouldn't be terrible to use "ILS number" -- following the lead of LUX. 

As I recall the other hold up with this issue was that we were waiting (with help from David P.?) to get a full extract of the bibliographic module in TMS, as the earlier extract was quite incomplete. With that extract, we could plot the best strategy for matching all possible entries with their corresponding ILS numbers.

**Comment by KraigBinkowski** [comment]
If LUX uses "ILS Number"  (Integrated Library System Number) then I don't see why we can't adopt that. 

Yes, the matching of the TMS bib entries with the Orbis bibIDs (ILS Number) is the issue. During our Dec. 18th meeting I agreed to supply a small group of 20 representative records for us be able to make some tests. Would this suffice in lieu of getting a full extract from David to start the process?

**Comment by edgartdata** [comment]
@KraigBinkowski Yes a few records to test would be great. Thanks.

**Comment by edgartdata** [comment]
@flapka @KraigBinkowski Now that we have settle on the name 'ILS Number", can you please confirm that we want to rename the TMS alternate number 'Control Number' (which are Orbis BibIDs) with 'ILS Number".
Once I get your green light I will request the change to David who will need to add it to his COBOAT script (as well as ISBN), so that these 4 types of alternate Bib numbers are pushed to LIDO:
- LC Call Number
- OCLC Number
- ISBN
- ILS Number

**Comment by edgartdata** [comment]
@yulgit1 Can we come back to my earlier question in this thread, which was: can you please confirm that you are using the TMS bib citations that we push to lido:relatedWorkSet for the LUX publications? lido:relatedWorkSet is where we vend publications external indentifiers (LC Call Number, OCLC Number, and coming up soon ISBN, and ILS Number).

You mentioned that "We are using the appellationValue for those that are "publication event", not the relatedWorkSet, as the former has the carets used for formatting italics.

But as long as the ordering is the same, which it is for B1977.14.77 checking the first few publications, we can pull the BibIDs that would be there. But looking now there are no bibIDs yet (Only LC Call Number, OCLC Number, and YCBA local):

https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:34&metadataPrefix=lido "

Are we okay with this solution then? leave the text formatting to the appellationValue and the 4 alternate numbers to lido:relatedWorkSet ?

**Comment by edgartdata** [comment]
@KraigBinkowski @flapka Here is the list of 907 titles in the TMS Bibliography Module that currently have 'Control Number' alternate number. (For some reason the numbers in the D column of the Excel list attached below are ISBN numbers. This is due to the TMS list view from which the Excel is derived. Sadly currently this list view is configured to print ISBN numbers, and no other alternate numbers).

![Control Number-soon to be ILS Number](https://user-images.githubusercontent.com/4093644/104646877-13ebfc00-567f-11eb-9b7b-049c12d304e8.png)


[YCBA TMS Bib Module records with Control Number alternate number (to become ILS Number).xlsx](https://github.com/ycba-cia/blacklight-collections2/files/5816883/YCBA.TMS.Bib.Module.records.with.Control.Number.alternate.number.to.become.ILS.Number.xlsx)

**Comment by yulgit1** [comment]
@edgartdata 

Yes for blacklight, this solution should work if the appellationValue of the publication events with formatting are in the same order as the IDs in the relatedWorkSet.

For LUX, v9 used the appellationValue with the caret's removed. If there is a v10, it would make more sense to use the relatedWorkSet just to be consistent, but the resulting citation string would be the same.

**Comment by edgartdata** [comment]
@KraigBinkowski I think I might have misinterpreted what should be renamed ILS Number in TMS. Is it Class Number or Control Number?

**Comment by KraigBinkowski** [comment]
It doesn't matter - ref doesn't use either field. The 907 records you have identified that have data in the control number field were populated when we exported bib records into TMS via Z39.50 protocol. It grabbed a bunch of fields we don't use. 
For simplicity sake I would recommend that we use CLASS NUMBER as the field for ILS Number.

**Comment by edgartdata** [comment]
@edgartdata to create the new ILS Number category.

**Comment by edgartdata** [comment]
@KraigBinkowski I have created the new Alternate Number Description ILS Number in the TMS Bib Module. You can start using now.
![YCBA Bib Module Alt Number Description ILS Number](https://user-images.githubusercontent.com/4093644/106294990-e1650600-621d-11eb-8b8e-5140a23eb21f.png)

**Comment by KraigBinkowski** [comment]
Perfect! Thank you.

Kraig

Kraig Binkowski
Chief Librarian
Reference Library and Archives

Yale Center for British Art

1080 Chapel Street

P.O. Box 208280

New Haven, CT 06520-8280

+1 203 432 2846 | +1 203 415 1192 mobile


britishart.yale.edu<http://britishart.yale.edu/>

Explore the Center's exhibitions<https://britishart.yale.edu/exhibitions> online.
Connect on Facebook<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FYaleBritishArt%2F&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312502268&sdata=cWFWX9dZKjaC9SiTfDHkWQmsW0fv5Y%2B9aaSfG%2FWSo%2BA%3D&reserved=0>, Twitter<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FYaleBritishArt&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312512260&sdata=IFyktJi9i3QXR94LWitH5svX0D%2F9pQ8Bb4Vjjm8BWGI%3D&reserved=0>, Instagram<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fyalebritishart%2F&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312512260&sdata=7hZ4%2BD6l1XUl13qTvjpB56lQ8hVH4VvnrhhR3lnKG4w%3D&reserved=0>, and YouTube<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fyalebritishart&data=02%7C01%7Clyn.rose%40yale.edu%7C02164475b8f54640e50d08d79f5be394%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637153089312522255&sdata=RQmjS7zAcuAEdlGLt55LVMHp7gds5pqmys3g2PPxlWk%3D&reserved=0> @yalebritishart #YCBA

**Comment by edgartdata** [comment]
https://collections.britishart.yale.edu/catalog/tms:1256 has ILS number recorded for Angus Trumble's Edwardian opulence publication. @yulgit1 Is it a good example for you to demo the solution for this issue, which *I think* is to link the BL Bibliography title to the BL Reference Library record. @yulgit1 @flapka can you remind me? Thanks

**Comment by KraigBinkowski** [comment]
The solution to this issue is the creation of the ILS field in TMS, which has been accomplished. The actual mapping and recording of the ILS numbers is more of a manual task that is ongoing now. The issue you refer to is issue #211 
Publications list -- link entries to full bib record in blacklight. That issue can be tested with https://collections.britishart.yale.edu/catalog/tms:1256  -  Angus Trumble's Edwardian opulence.

**Comment by edgartdata** [comment]
Thanks @KraigBinkowski So I take it is okay to close #279 and circle back to #211?

**Comment by KraigBinkowski** [comment]
Yes, I think so

**Comment by edgartdata** [comment]
Ok, so I am closing this issue with the plan to follow up on #211 soon.
