### ISSUE TITLE
eshop URLs

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#297]
Today 4/1 I showed Anissa how to add touchNet URLs into TMS (Objects Module/Notes tab/Text Entries/LIDO-eshop product URL:

![image](https://user-images.githubusercontent.com/4093644/113303066-b2771900-92ce-11eb-9780-1e5ac999b8ab.png)

**Comment by edgartdata** [comment]
Question to the group:
- what is the heading for these links in the BlackLight detailed object records? do we need a heading (on the model of the metadata column in object records?
- what is their shape? Is it a generic button that says the same thing in all object records but hyperlinks to different eshop URLs?
- when an eshop product is a book, such as https://secure.touchnet.net/C20510_ustores/web/product_detail.jsp?PRODUCTID=199&SINGLESTORE=true, does each work in the publication get a eshop link in the BL detailed object records? 
- or are publications sold in the eshop linked to our Reference Library BL records for this titles instead?

**Comment by yulgit1** [comment]
Was thinking of a "Purchase Related Objects" or "Object in Museum Store" button on the button row.  

Question, if multiple museum store objects apply, will there be multiple objects on the touchnet site, or multiple touchnet URLs to display on the object record?

Regarding EDG's last 2 bullet points, seems if an object is in the book, display the eshop link for the object.  The association should be obvious, the naive user looking at an object isn't likely to go the Bibliography section, find the appropriate book, traverse to that page, and then click to buy the product, they should be able to see the buy button immediately with the object.

**Comment by flapka** [comment]
Do we have a mandate from YCBA leadership to add such links to Blacklight? (Apologies if I missed this topic when discussed previously). If we do have a mandate, is the expectation that we we apply such links exhaustively?

**Comment by edgartdata** [comment]
@yulgit1 Good question about a BL object record having several links to several different products in the eshop. I have been told that several TMS object records can have one and only eshop URL but you are asking about the reverse scenario and I don't know.

To @yulgit1's suggestion: my sense is that it might not be sustainable to link all object records to their publications that are sold in the eshop because entering the eshop URLs in TMS would be done by a member of the Web team. For example _Paul Mellon's Legacy_ exhibition catalog has 240+ objects in it. If this is the mandate though, I would suggest that we prepare the list of objects in each publication for them.

To @flapka's question, I will let @robl answer as he has been working with the Web team and I understand that Courtney made the request to them. Rob, please correct me if I am wrong.

**Comment by robl** [comment]
Hi all, to catch a few of the questions above,

_Do we have a mandate from YCBA leadership to add such links to Blacklight?_

Yes, having such a link in BL when relevant is based on communication from the Director to the website project team last fall.

_What is the heading for these links in the BlackLight detailed object records? do we need a heading (on the model of the metadata column in object records?_

Display is TBD, but so far some of us have been thinking that a button (which would only display when there is a URL) would be best, in part because it would be so clearly different from the many text-based links in object-record pages. This would help to clue in visitors that it is different from those many other links in regard both to its nature and its destination.

_What is their shape? Is it a generic button that says the same thing in all object records but hyperlinks to different eshop URLs?_

If it is a button, shape is TBD. I recommend strongly that for maintenance reasons, the label text on that button always be the same (that is, that it simply be flat text in the page template, not fielded text transported from TMS), and that only the single shop URL to which it leads is variable (based directly on what has been transported out of TMS).

_When an eshop product is a book, such as https://secure.touchnet.net/C20510_ustores/web/product_detail.jsp?PRODUCTID=199&SINGLESTORE=true, does each work in the publication get a eshop link in the BL detailed object records?_

This, I would currently imagine, might be a judgment call from the Shop side; but I would be extremely surprised if it were the case, since it would so often confuse people who end up on a shop page for a book that has no apparent relationship to the object (even if its undescribed-in-the-shop page 237 has a catalog entry for the work...).

_If multiple museum store objects apply, will there be multiple objects on the touchnet site, or multiple touchnet URLs to display on the object record?_

There will always only ever be one link (with a button) or zero links (with no button) from any given BL page to the shop. Each shop item does have its own page on the TouchNet site, but any aggregation (to enable a single link) of multiple shop pages for shop items that represent the same collections object will be handled on the shop's TouchNet platform; so there will never be a need for more than one URL or button on the TMS-to-BL side. In BL, there will always be either one button and one link, or no button and no link. This was an intentional aspect of working out the approach on the TouchNet side, with the express purpose of avoiding build/maintain headaches and display clutter on the BL side (never a BL object page with tons of buttons each to a different individual shop URL, and no need for TMS-to-BL IA to handle multiple instances or aggregation on behalf of the shop).

Hope this helps! Happy to field more if I can.

**Comment by edgartdata** [comment]
@robl Here is my mapping of our e-shop links to the LIDO XML schema:

 <lido:relatedWorksWrap>
<lido:relatedWorkSet>
                    <lido:relatedWork>
                        <lido:displayObject>https://secure.touchnet.net/C20510_ustores/web/product_detail.jsp?PRODUCTID=199</lido:displayObject>
                        <lido:object>
                            <lido:objectWebResource/>

                            <lido:objectNote></lido:objectNote>  
                        </lido:object>
                    </lido:relatedWork>
                    <lido:relatedWorkRelType>
                        <lido:conceptID  lido:type="local" lido:source="YCBA e-shop link"></lido:conceptID>
                        <lido:term>YCBA e-shop link</lido:term>
                    </lido:relatedWorkRelType>
                </lido:relatedWorkSet>

[many other <lido:relatedWorkSet>...</lido:relatedWorkSet> for publications]

 </lido:relatedWorksWrap>

It validates in Oxygen for me.

There are 3 differences between the  <lido:relatedWorkSet> for e-shop links and  <lido:relatedWorkSet> for publications:

- <lido:relatedWorkSet> for e-shop links doesn't need <lido:objectID> elements
- <lido:relatedWorkRelType> has a different value for the lido:source attribute in  <lido:conceptID> ('YCBA e-shop link' instead of 'publication')
- <lido:term> is 'YCBA e-shop link' (instead of 'related to')

  <lido:relatedWorkSet>
                    <lido:relatedWork>
                        <lido:displayObject></lido:displayObject>
                        <lido:object>
                            <lido:objectWebResource/>
                            <lido:objectID lido:type="local" lido:source="LC Call Number">Yjg95 993Se (SML)</lido:objectID>
                            <lido:objectID lido:type="local" lido:source="OCLC Number">31929435</lido:objectID>
                            <lido:objectID lido:type="local" lido:source="YCBA TMS Bibliographic Module record referenceID">2580</lido:objectID>
                            <lido:objectNote></lido:objectNote>  
                        </lido:object>
                    </lido:relatedWork>
                    <lido:relatedWorkRelType>
                        <lido:conceptID  lido:type="local" lido:source="publication"></lido:conceptID>
                        <lido:term>related to</lido:term>
                    </lido:relatedWorkRelType>
                </lido:relatedWorkSet> 

Let me know if you need me to copy this into the TMS GitHub for David.

**Comment by edgartdata** [comment]
David updated LIDO yesterday to accommodate for TouchNet links and pushed his code to production for https://collections.britishart.yale.edu/catalog/tms:34 

Next steps: 
- where do TouchNet links live in BL records?
- what do they look like?
- what text should an e-shop button display?

**Comment by edgartdata** [comment]
Deploy in BL DEV blue button to the right of "Request additional photography" with text "Visit museum shop for related items"

Next step: check with RBMS items. @flapka

**Comment by flapka** [comment]
@edgartdata When last I checked, there were no RBM related items in the eshop.

**Comment by edgartdata** [comment]
@flapka Okay, thanks for confirming. I thought I saw shop items with images from the Helmigham Bestiary in the past (many many months ago) but I could be wrong.

If there are any in the future, because the mechanics of publishing them to the online catalog would be different, it might be helpful to let Anissa know sooner rather than later. @robl Do you have a sense if there are any RBMS in the e-shop pipeline?

**Comment by robl** [comment]
@edgartdata, I'm basically not in the loop regarding shop content (I just see an occasional example of a current item if it illustrates some general issue). The best bet would be to check with Anissa, who manages all shop content. Thanks!

**Comment by edgartdata** [comment]
@robl Okay so once we have a DEV example to show Anissa, I am happy to reach out to her to let her know and ask about RBMS items.

**Comment by robl** [comment]
That sounds perfect, @edgartdata.

**Comment by yulgit1** [comment]
modified xslt, indexing overnight:
https://git.yale.edu/ermadmix/ycba_xslts/commit/13da8772cc92628d8d4eb668c75330e02a0301f7

**Comment by yulgit1** [comment]
Item page with eshop button:
https://collections-test.britishart.yale.edu/catalog/tms:34
https://collections-test.britishart.yale.edu/catalog/tms:5005 (ex without eshop link)

What do you think?

**Comment by robl** [comment]
It's looking good! The text label is close to being too long, but I think it works, and I'm not thinking of a shorter version that would not sacrifice clarity. My two cents would be: we’re basically there.

As a side note about a different button, I’d suggest that for consistent type treatment, the “Download/Print Selected Image” text could become “Download/Print selected image” to match the sentence case elsewhere (e.g., “Request additional photography”). That became noticeable to me once we had the shop button there as well, and it would harmonize with the general use of sentence case rather than title case on the Drupal site as well.

**Comment by edgartdata** [comment]
All, let me know if you have comments, suggestions or concerns about this. I would like to address our feedback before I show anything to Anissa, in case we can think of changes.

**Comment by yulgit1** [comment]
Will there be non-TMS (Ref/RB) eshop entries? If so I could imagine creating a small form with 2 text fields, orbisID and eshop link that would populate a small table hooked up to the collection ingest app.

**Comment by edgartdata** [comment]
@yulgit1 I will check with Anissa once this group has confirmed the design that we want to put to her and Beth. And good to hear that if we do have RBMS e-shop products, it might not be too difficult to add them to BL.

**Comment by flapka** [comment]
@yulgit1 's suggestion is appealing. A table such as that would be preferable to putting the link in the source MARC record, due to policy concerns.

**Comment by edgartdata** [comment]
Just noting here that I have shared what e-shop buttons/links look like in the development instance of our online collections catalog: https://collections-test.britishart.yale.edu/catalog/tms:34 with Anissa and asked her if the text satisfactory. I have not heard back yet.

**Comment by edgartdata** [comment]
Rob will talk with the Web team later today to let them know that the dev version will be back shortly.

**Comment by edgartdata** [comment]
Resent this screen shot to Anissa today:
![YCBA_e-shop_button_for_Turner_Dort](https://user-images.githubusercontent.com/4093644/123470859-f5d9de80-d5c2-11eb-96e5-7c118f77a531.png)

**Comment by edgartdata** [comment]
@yulgit1 and all,

I just got these updates from Anissa: 

- Beth approves the look and feel of the eshop button in the online catalog
- A small edit needs to be made to the text: “Visit our Museum Shop for related items” (with Museum Shop capitalized)
- eshop links in the online catalog will only be for exhibition catalogue links, and not any other custom products
- It is okay to push this to production now (even though only _Dort_ has an eshop link today
- I am meeting with Anissa again on August 9 to train her on how to add more eshop links to TMS

**Comment by yulgit1** [comment]
Fixed: A small edit needs to be made to the text: “Visit our Museum Shop for related items” (with Museum Shop capitalized)

**Comment by edgartdata** [comment]
@yulgit1 Beth is asking if we can change the e-shop button text to "See Museum Shop for related items" in the hopes that it all fits in one line.

**Comment by yulgit1** [comment]
@edgartdata Should be all set. Should say though that the fit in one or two lines depends on the width of your browser window.  For the most part this will now display on one line, and this fixes it for most widths, but if you play with the browser width there is a width where the button goes to 2 lines before the other buttons do.
