### ISSUE TITLE
Vend TMS dimensions with description to LUX v10 data

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#310]
This is related to https://github.com/ycba-cia/TMS/issues/22

Example of dimension with description: https://collections.britishart.yale.edu/catalog/tms:40842

Sheet (cropped inside plate; top and bottom edges significantly torn): 15 9/16 × 9 5/8 inches (39.5 × 24.4 cm) and Image (two images; span of both images measured): 14 × 9 3/16 inches (35.5 × 23.3 cm)

**Comment by MarkAronson** [comment]
Aronson leaving a comment for the first time:  what is the issue here?  Or why is the comment about the torn edges included in the data about dimensions?  Are dimensions not dimensions?

**Comment by yulgit1** [comment]
@MarkAronson - Welcome, and I believe this was addressed and resolved, just this issue here hasn't been updated and closed. Previously this field didn't vend the "(cropped inside plate; top and bottom edges significantly torn)" and "(two images; span of both images measured)" part.

@edgartdata OK to close?

**Comment by edgartdata** [comment]
@MarkAronson @yulgit1 Yes, this issue has been resolved. The problem was that the description of the dimension (which could be more detail about what is being measured, or more detail about how the object is measured) that is in TMS was not being vended to the online collections catalog. I worked with David and Eric to fix it so I am now closing the issue.
