### ISSUE TITLE
View types and image captions

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#312]
From Mark and Ed:

Per discussion we are proposing the On line Catalogue feature these photographs of paintings only:

a.	“beauty” cropped shot  (note Conservation does not consider this “beauty”)
b.	Front unframed with color bars
c.	Front framed with color bars
d.	Back  - one view only – framed with color bars  (if there is a view with backing board and a view without – I imagine view without backing board is preferred.)
e.	X-radiography if it exists
f.	IR if it exists

Captions:

NO BEFORE/DURING/AFTER captions but rather default to what the standard caption would be.

-----
@yulgit1 @mxgold I imagine that not publishing image captions to the online catalog also means not sending image captions to the IIIF manifests (image captions would probably need to stay in NetX for internal management purposes though?). Are there other technical issues or dependencies to consider?

**Comment by yulgit1** [comment]
@edgartdata Yes, so as you know the images and captions you see in the online catalog are from the IIIF manifests.  Which images get exposed in the manifest are controlled by those "CDS Access JPEG", "CDS Access Master", "CDS AccessTIFF" fields in NETX, and the captions for each of these images are sourced from what is entered in the NETX "Image Caption" field. CDS2 also inserts a default caption when a caption is not in NETX, like "x of y Image from Yale University". No more, no less.

**Comment by edgartdata** [comment]
@mxgold @yulgit1 Given Mark's requests above, do you have all the elements to act on it? 

If the public facing captions are not mentioning BEFORE/DURING/AFTER anymore but instead are 'front, framed' for example, would this need a bulk change in NETX? What I mean is if BEFORE/DURING/AFTER captions are useful for internal image management purposes but are not shared with the manifests/BL, does that mean we need 2 captions per image, one technical/internal and the other one not technical/public? Is it possible? Do you have other thoughts on this?

**Comment by yulgit1** [comment]
@mxgold @edgartdata So CDS2 uses the NETX ImageCaption in the manifests, so that could remain the public/not technical caption.  Did we recently discuss with Rare Books using NETX Tombstone field?  Perhaps this could be the technical/internal caption field?

**Comment by mxgold** [comment]
The contents of the current caption field which are displayed in Mirador (IPTC:Description = NetX:ImageCaption) are an edited, public version of IPTC:Keywords / NetX:ImageKeywords.  It is therefore possible to simply remove before/during/after or whatever else Mark/Ed wish from NetX:ImageCaption and public display but retain for our own image management purposes in ImageKeywords.

**Comment by mxgold** [comment]
The sum of the proposed changes will require reviewing each object record and its associated image assets one by one to publish/unpublish views as needed, reorder display via rank, and edit public facing captions.  Bearing in mind Imaging will require several weeks to divide and work through, is the level of priority / internal deadline known?

**Comment by edgartdata** [comment]
@mxgold @yulgit1 When there are several BEFORE/DURING/AFTER treatment captions for one object, whenever possible the goal is to only publish images for that object that are AFTER treatment with a caption that would not mention 'After treatment' but just 'front, framed'.
Is it possible to bulk filter out the before and during images from the online collections catalog altogether? (of course we would want to retain the before and during images in NetX for internal purposes).

I guess when a work has not had a treatment we publish its most recent image, also with the default  'front, framed' caption.

Because this is a long term change in our image publishing practice, can we focus on the paintings, and maybe the short list of priority paintings that Ed has identified? @EdwardTown1

**Comment by yulgit1** [comment]
Would bulk TMAN SQL help?  For example, the following is all the "before treatment" in TMAN, which could be updated to remove the "before treatment" in batch.

[before_treatment.xlsx](https://github.com/ycba-cia/blacklight-collections2/files/6896390/before_treatment.xlsx)

```
select assetid,filename,imagetitle,cdsrank,imagecaption,imagekeywords,cds_access_master,cds_access_tiff,cds_access_jpeg
FROM [TMAN].[dbo].[assets]
where unitcode = 'YCBA' and imagecaption like '%before treatment%'
```

**Comment by edgartdata** [comment]
@yulgit1 We have been asked to not publish the before and during treatment shots anymore. So for these 2 types of shot, there is no caption to bulk update.
The captions to bulk update would only be for the after treatment shots, which should not have 'after treatment' in them anymore.

**Comment by yulgit1** [comment]
@edgartdata - Yes that's what I meant, use a query like that to identify 'after treatment', remove the 'after treatment' from the imagecaption field, and use the cds_access_x fields to publish/unpublish in batches.

But published or not, would you want to remove the before/during/after from imagecaption for consistency? And of course still maintain the imagekeywords as the full internal caption?

**Comment by mxgold** [comment]
@yulgit1 bulk TMAN SQL and bulk updates could help with some of the things we need to do that you've identified:  a query like that to identify 'after treatment', remove the 'after treatment' from the imagecaption field, and use the cds_access_x fields to publish/unpublish in batches. (If you have the time to work with Imaging on that, gratefully accepted!)  However, I'm not sure there's a predictable way (or at least, a sufficiently uncomplicated + predictable way) to bulk correct the display order of images via rank, given the variability across image sets  - so that may still need to be done via visual review and manual NetX changes.  However, I'll think more carefully about how that might work.
@edgartdata  - Ed and Mark wish to exclude detail shots? We don't have have them for many works, but we have published them when available (ex: B1977.14.77)

**Comment by edgartdata** [comment]
7/30/21: 

- The decision was made to not publish image details anymore.
- @m Should we keep raking light images?
- We will need standardized guidelines for images for sculptures
- Melissa will work on a set of images per the new guidelines and check back in with this group

Noting here that resorting images by rank and bulk updates will be 2 difficult tasks that will take time.

**Comment by edgartdata** [comment]
@mxgold from Mark: no raking light shots in the online catalog anymore.

**Comment by yulgit1** [comment]
In case others experience the same issue, that link is redirecting me to: https://github.com/ycba-cia/blacklight-collections2/issues/url

It's like GitHub is blocking it.  I had to copy out that link directly to my browser.  When I got to the Sharepoint site had to request access, which I'm waiting for now.

**Comment by clemgreen** [comment]
Apologies for the link issue and thanks Eric for the tip

If anyone wants to see the document not via SharePoint, I've attached it here as a Word Document as well

[Sample-images of YCBA paintings online.docx](https://github.com/ycba-cia/blacklight-collections2/files/7100648/Sample-images.of.YCBA.paintings.online.docx)

**Comment by edgartdata** [comment]
Let's make some time tomorrow to consider imaging P&D questions.

**Comment by annabozz** [comment]
Hi all-

Here are some updated guidelines (for YCBA Paintings records) we went over during the Online Collections meeting 9/10:

**Order of images to appear for online record- revisiting guidelines from before:**

1. cropped to image, recto (pub)
2. recto, unframed (bar)
3. recto, framed (bar)
4. verso, framed (bar) – one view only, if there is a view with backing board and view without, use view without backing board
5. x-radiograph (bar) if exists
6. infrared reflectogram (bar) if exists

 **Captions:**

NO BEFORE/DURING/AFTER captions but rather default to what the standard caption would be.

 **Other notes:**

1.       _use of Image Caption "framed" or "unframed" for first beauty cropped in, pub image displayed online for records_

·         this will be revisited and some examples from 1900-now will be looked at. samples to be brought forth in future meeting for discussion/review


2. _conservation images:_

- xray: publish, use Image Caption "x-radiograph", don't use caption "composite" for online view but keep that in NetX Image Keywords for information purposes

- IR: publish, and use Image Caption "infrared reflectogram”

- raking light: don't publish

- UV: don't publish

details: don't publish


3. _if earlier treatment status shows a framed, recto shot or framed, verso shot, still publish these shots if only representative shots of these views, even though in the sequence there will be after treatment images mixed in with these_

 A few extra questions from Imaging:

- is there a preference for image captions, i.e. "rect, cropped to image" or "cropped to image, recto"
- can we double confirm that no verso, unframed shots will be published online? I'm looking back to the notes where it says one view only of verso

**Comment by bobhixon** [comment]
Thanks Anna!

From: Anna Bozzuto ***@***.***>
Reply-To: ycba-cia/blacklight-collections2 ***@***.***>
Date: Wednesday, September 15, 2021 at 3:50 PM
To: ycba-cia/blacklight-collections2 ***@***.***>
Cc: "Hixon, Robert" ***@***.***>, Mention ***@***.***>
Subject: Re: [ycba-cia/blacklight-collections2] View types and image captions (#312)


Hi all-

Here are some updated guidelines (for YCBA Paintings records) we went over during the Online Collections meeting 9/10:

Order of images to appear for online record- revisiting guidelines from before:

  1.  recto, cropped to image (pub)
  2.  recto, unframed (bar)
  3.  recto, framed (bar)
  4.  verso, framed (bar) – one view only, if there is a view with backing board and view without, use view without backing board
  5.  x-radiograph (bar) if exists
  6.  infrared reflectogram (bar) if exists

Captions:

NO BEFORE/DURING/AFTER captions but rather default to what the standard caption would be.

Conservation images:

  *   xray: publish, use Image Caption "x-radiograph", don't use caption "composite" for online view but keep that in NetX Image Keywords for information purposes
  *   IR: publish, and use Image Caption "infrared reflectogram”
  *   raking light: don't publish
  *   UV: don't publish
  *   details: don't publish

if earlier treatment status shows a framed, recto shot or framed, verso shot, still publish these shots if only representative shots of these views, even though in the sequence there will be after treatment images mixed in with these

Outstanding questions/etc.:

1. use of Image Caption "framed" or "unframed" for first beauty crop, pub image- as per 9/10 meeting, this is undecided and will be revisited and some samples from 1900-now can be looked at in a future meeting for discussion/review

2. can we double confirm that no "verso, unframed" shots will be published online? I'm looking back to the notes where it says one view only of verso framed.. this may be confusion on my part. Include "verso, unframed" first or do not include? (new question)

________________________________

UPDATE 9/15:

@MarkAronson<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarkAronson&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539280141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dAmGk6Kzh5%2BoFDnHajOXB7k5slm9RTo3G2ZkxXq0aas%3D&reserved=0> @EdwardTown1<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEdwardTown1&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539280141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UjSqztgiSA%2BHI82lhelGuQhCGRtki6pmPa%2F0oGo94bA%3D&reserved=0> @edgartdata<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fedgartdata&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539290148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M6RIcG2GBfpo33EgH3UasF2W4IXT3LciFx8B2n4RvIM%3D&reserved=0> @mxgold<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmxgold&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539300132%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B0IhL0omhfJvZekk5UX62o%2Fw8qWuGNQ2CFlZs0GxHzc%3D&reserved=0> @bobhixon<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbobhixon&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539300132%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pfumjdcvi9IrNGh0XfBks73sZA8KYawolpSV3mEPHco%3D&reserved=0>

Hi all, the Imaging Department (Bob and Anna) is ready to dive in and start making the above changes to the paintings records online if there are no objections to the things we agreed upon, listed above. Lingering questions are in bold.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fycba-cia%2Fblacklight-collections2%2Fissues%2F312%23issuecomment-919397073&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539310133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M9Gan9%2B3ChjRRRk2CWc048NGeWNtO4jyj6%2B9d2N%2BGjQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATSA24MEXHT2DKC5Y2EETO3UCD2JXANCNFSM5ALSYTMA&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539320123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LeVXk9FjGa%2BmkVPQHQ9z9y6KMKiA6Uw9dcSXif1Owl8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crobert.hixon%40yale.edu%7C5edad170ab714de78b2d08d978821f8e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637673322539320123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ctrG4PeMpTcN2arYGVBOdLglfAmv7by2O7E%2By6ZliqA%3D&reserved=0>.

**Comment by edgartdata** [comment]
In general framed verso preferred over unframed verso so we have only 1 verso shot.

For the rare shots with backing board, consider if there is interesting information on it. If yes, then publish it.

Add 'backing board' for NetX caption.

Polarized versus unpolarized shots: choose polarized 

If we only have a before treatment infrared: publish it but do not mention 'before treatment' in the public facing caption.

**Comment by edgartdata** [comment]
The group should email Melissa, Anna, and Bob when we see instances of images and captions that do not follow our new guidelines.

**Comment by bobhixon** [comment]
Hi all,

We are chipping away at this list and would like some clarification on polarized vs. unpolarized images. I’ve run into several framed objects shot with and without polarizers and there is a drastic difference between them. As you can see from the attached, polarization and frames do not work well together. Should we stick with unpolarized framed recto images?

Best,
Bob

From: Emmanuelle Delmas-Glass ***@***.***>
Reply-To: ycba-cia/blacklight-collections2 ***@***.***>
Date: Friday, September 24, 2021 at 9:50 AM
To: ycba-cia/blacklight-collections2 ***@***.***>
Cc: "Hixon, Robert" ***@***.***>, Mention ***@***.***>
Subject: Re: [ycba-cia/blacklight-collections2] View types and image captions (#312)


In general framed verso preferred over unframed verso so we have only 1 verso shot.

For the rare shots with backing board, consider if there is interesting information on it. If yes, then publish it.

Add 'backing board' for NetX caption.

Polarized versus unpolarized shots: choose polarized

If we only have a before treatment infrared: publish it but do not mention 'before treatment' in the public facing caption.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fycba-cia%2Fblacklight-collections2%2Fissues%2F312%23issuecomment-926640672&data=04%7C01%7Crobert.hixon%40yale.edu%7Cea1b5a4d145846890dd408d97f624ab4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637680882404824179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GeaTICQoUETaT8LE6Pk23cWVdvJpABKFxZkYTSj4aac%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATSA24ID2QQD3JAOTXGSXVLUDR625ANCNFSM5ALSYTMA&data=04%7C01%7Crobert.hixon%40yale.edu%7Cea1b5a4d145846890dd408d97f624ab4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637680882404834173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FAPz7pOsMn9JZWNcZWSbsV6B2fIhRjI6qXJOy1KBOPw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crobert.hixon%40yale.edu%7Cea1b5a4d145846890dd408d97f624ab4%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637680882404844168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kgj%2FKhprKTe8ZcK1Cq6punBk6J%2FBc2OVOWoK1UI92Wc%3D&reserved=0>.

**Comment by annabozz** [comment]
Update in response to question about including the keyword "unframed" for online catalogue for related images (Paintings):

•	overall, include the keyword “unframed” for paintings (bar images, recto and verso)

•	exceptions: don’t include the keyword “unframed” for contemporary paintings that don’t have a frame (bar images, recto and verso)

**Comment by edgartdata** [comment]
@bobhixon Do you still need clarification on polarized vs. unpolarized images?

**Comment by bobhixon** [comment]
@edgartdata I took care of those early on. Have you seen any that slipped through?

**Comment by edgartdata** [comment]
@bobhixon No, I have not. I am just circling back to issues to see if I can close them. Thanks.
