### ISSUE TITLE
New P&D sketchbooks

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#362]
@LaurelOP Laurel, feel free to enter the sketchbooks we should work on next. Thanks!

**Comment by LaurelOP** [comment]
Hi @edgartdata 

Here is the list that David, Amelia, and I put together.

Many thanks!

Flaxman's Italian Sketchbook  B1975.3.468
Simpson Sketchbook from Calcutta to Peshawar B2014.21.2
Clarkson Stanfield sketchbook B1988.4
Blake Songs of Innocence and Experience B1992.8.13
Bodichon Sketchbook B1991.23.2

**Comment by edgartdata** [comment]
@LaurelOP Would you also consider the Bardwell sketchbook https://collections.britishart.yale.edu/catalog/tms:58388 ? The potential issue with it is that we don't have titles for all its pages, but we have its provenance.

The other potential sketchbook could be the vol.3 of Hodges Views of India https://collections.britishart.yale.edu/catalog/tms:54652

**Comment by LaurelOP** [comment]
@edgartdata I consulted with Charlotte about the Bardwell. She's still putting in descriptive titles, but will be in touch with us when that's done.

Hodges can be added to the list. Though, with all of the Hodges albums, we are working on re-cataloguing some of the names. So there may be re-editing that needs to happen in NetX. (But since the first two are already done, it probably makes sense to do Vol. 3.)
