### ISSUE TITLE
P&D Flaxman's Italian Sketchbook B1975.3.468

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#365]
@annabozz Flaxman's Italian Sketchbook B1975.3.468 https://collections.britishart.yale.edu/catalog/tms:53744 has 79 pages. Looks like all of them have been digitized. 

@LaurelOP What masonry image would you like?

**Comment by LaurelOP** [comment]
I'd suggest 25r--the sketch of Michelangelo's Night.

Many thanks @edgartdata and @annabozz !

**Comment by annabozz** [comment]
- started re-ranking images online 
- preparing masonary image for ingest

**Comment by annabozz** [comment]
DONE:

- masonary image published online (other page spreads were already published)
- TMS media images rank sorted/cleaned up

TO DO:

- there are captions via showing what recto and verso they are, already in the images. not sure if this is ok, but Anna will send NetX Collection to Amelia and David on Monday (Amelia out of office rest of week)
otherwise, records all set on Imaging's part: https://collections.britishart.yale.edu/catalog/tms:53744

**Comment by annabozz** [comment]
Update!

Anna was delayed on sending image captions to Amelia and David for this sketchbook- just sent today.

Unless I hear otherwise I will keep the single pages in TMS (won't delete media files) that are in the overall record.

**Comment by edgartdata** [comment]
Just to confirm/document here that P&D are in favor of keeping the single page shots in TMS. @LaurelOP Please correct me if that's not correct.

**Comment by LaurelOP** [comment]
Yes, let's keep the single page shots. Thanks for checking, @edgartdata !

**Comment by edgartdata** [comment]
![Flaxman Italian sketchbook](https://user-images.githubusercontent.com/4093644/166246963-1230e107-9550-41f0-819e-57b6b1d44686.png)

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "Study of Night by Michelangelo, Tomb of Giuliano de' Medici, Church of San Lorenzo, Florence"

1. duplicate file (ba-obj-53744-0090-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-53744-0033-pub)
