### ISSUE TITLE
"Rights" facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#37]
facet for "rights" 

What to call it? "Image Use" "Status of the Work of Art", something else?

What for values? "Public Domain", "Copyrighted", and "Copyright Unknown"

For LIDO can use:<lido:rightsHolder>
<lido:legalBodyName>
<lido:appellationValue>Public Domain</lido:appellationValue>

How to derive for RBs?

**Comment by yulgit1** [comment]
@flapka How to derive for RBs for values "Public Domain", "Copyrighted", and "Copyright Unknown"

Incidentally this field is displayed on the right hand side of the show page.  In the following example the "Public Domain" link resolves to a handle representing "Public Domain" indexed in the rightsURL_ss field derived from: 

rightsURL = REXML::XPath.first(xml, '//lido:legalBodyID[@lido:type="URL"]')

http://hdl.handle.net/10079/w6m90dq

https://ycba-collections-dev.herokuapp.com/catalog/3623852

**Comment by flapka** [comment]
If the focus of this data element is *object* rights, then the values are (or will be) recorded in 542 $l (that's an 'L'). 

If we want a URI for the rights status, we (Melissa and RB) have talked about recording -- in 542 $u -- the URI for the concept in PREMIS, e.g.: http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk

**Comment by yulgit1** [comment]
General availability filter/facet: <link>

**Comment by flapka** [comment]
For the rights facet, the string value will come from 542 $l (that's an 'L'). But be aware that this data appears in almost zero records *so far* -- more coming soon.

**Comment by edgartdata** [comment]
I would suggest Item Rights for the name of this facet. Melissa?

**Comment by flapka** [comment]
Item Rights sounds good to me too.

**Comment by yulgit1** [comment]
@edgartdata - here's a list of the 13 'right reserved' and 1 'contract restriction (all)'

https://gist.github.com/yulgit1/6bc644a3424ff658f5d8a43e9c1278e9

**Comment by mxgold** [comment]
re: Mapping questions earlier in thread, for art collections

3 public facing rights values, as in the  current online collection, are fine.  However, shall we adhere to LOC scheme vocabulary as we move forward?  copyrighted, public domain, unknown

As discussed in the meeting, there are a greater number of Object Rights Types (ORTs) in TMS for the art collections, all of which may be mapped to one of the three public facing values.
 
"Rights reserved" can map to "copyrighted"
Contract restricted is trickier.  This would be a work/image of a work otherwise in the public domain, but whoever photographed the work maintained copyright in the photography.  (the single object in the online collection with this status at present is long term loan to the UK; the borrowing institution photographed it and was not open concerning permissions.)  For simplicity’s sake, we can map "contract restricted" to "copyrighted" as well.

**Comment by mxgold** [comment]
I prefer "Object Rights" over "Item Rights" but either is fine.

**Comment by yulgit1** [comment]
@flapka 
re 542 $l
since so many aren't recorded yet should the default be 'unknown'? (rather than nothing being represented in the facet?)

**Comment by flapka** [comment]
@mxgold Melissa, what do you think? I suppose defaulting to "unknown" would be okay.

**Comment by flapka** [comment]
Summary of our discussion last week: 

* Item rights [object_copyright_status] maps from MARC 542 $L. In absence of a 542 $L value, default to "unknown"
* Item rights url [object_copyright_status_url] maps from MARC 542 $u. In absence of a 542 $u value, default to "http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk"
* Item rights notice [object_copyright_notice] maps from MARC 542 $f. In absence of a 542 $f value, default to "Copyright unknown" (is that the same label used for art collections?)
* Item rights holder [object_copyright_holder] maps from MARC 542 $d. In absence of a 542 $d, leave null.
* Item rights holder role [object_copyright_holder_role] If 542 $d is not null, value = "rights holder"; else null

**Comment by edgartdata** [comment]
@mxgold to take of B1981.25.748 and B2012.3 (most probably get YCBA new photography)

**Comment by mxgold** [comment]
B2012.3 resolved; B1981.25.748 still on long term loan to UK, hope to commission photography w/ YCBA rights but may be some time.

Melissa Gold Fournier
Head of Imaging and Intellectual Property
Program Manager, YCBA West Campus Initiatives
YALE CENTER FOR BRITISH ART
britishart.yale.edu<http://www.britishart.yale.edu/>
