### ISSUE TITLE
Cozens Roman sketchbook B1978.43.166

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#404]
Alexander Cozens, Roman Sketchbook B1978.43.166 https://collections.britishart.yale.edu/catalog/tms:18383
From TMS: Eighty-seven pages of laid paper (27 removed), bound in vellum
A 'Roman Sketchbook' containing sixty pages numbered in order 2 through 87, with fragments and indications of missing pages

@LaurelOP What should be the hero image for the masonry view?

**Comment by LaurelOP** [comment]
Let's keep the title page as the hero image: https://collections.britishart.yale.edu/catalog/tms:18383

**Comment by annabozz** [comment]
Individual pages already photographed/ingested into record cover to cover with appropriately file names for this sketchbook.

B1978.43.166 (overall record)

- edited CDS levels to make sure all records published online
- set CDS Primary = 2 for masonry image: ba-obj-18383-0006-pub
- checked TMS records

TO DO:

- send NetX collection to Amelia and David for Image Caption step

**Comment by annabozz** [comment]
Hi @LaurelOP,

This object required light cleanup- before I send to Amelia and David for the Image Captions step, I had two questions at your convenience:
https://collections.britishart.yale.edu/catalog/tms:18383

1.  Was the below the correct title page for masonry display?

<img width="852" alt="Screen Shot 2022-10-05 at 9 10 07 AM" src="https://user-images.githubusercontent.com/74676099/194068476-4db8bdfd-ac4a-468e-862c-d657ca3941f7.png">

2. Do you want the last 6 single pages shown in the overall record to be displayed online? Right now they are published and showing after the back cover

**Comment by LaurelOP** [comment]
Thanks for checking on this @annabozz. I'm not sure why I had said the title page (and wonder if I was thinking of something else!)

Instead, I think we should use the image before the endpapers: 
![image](https://user-images.githubusercontent.com/99691490/194139561-675b5bae-e901-4d2c-9c9f-069953a79ce0.png)

And, along those lines, I think that this sketchbook should probably be rotated as well, since the majority of the images are landscape, if that's not too much trouble.

As for the loose pages--yes, let's keep them as is, after the cover.

Let me know if there are any more questions--and thank you!

**Comment by annabozz** [comment]
Thanks for clarifying. I changed the masonry image.

For rotating this sketchbook we would need to do the same delete/replace function as the William Simpson book (https://github.com/ycba-cia/blacklight-collections2/issues/367) so we can replace images to rotated view when Preservica migration is done. 

Adding this as a second one to keep an eye for

**Comment by edgartdata** [comment]
Input page titles after they are rotated to avoid duplication of work.

**Comment by edgartdata** [comment]
BlackLight records for individual pages deleted.
